[build]
  command = "node write-firebase-config.js"
  publish = "."

[[headers]]
  for = "/data/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-store"